### ISSUE TITLE
Gradle 4.1 RC-1 fails to build

### ISSUE THREAD

**Issue by scruffyfox** [bitrise-io/steps-gradle-runner#43]
Im getting an issue with the latest version of the runner 

```
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Gradle task failed, error: exit status 1
```

currently using the latest version of Gradle `https://services.gradle.org/distributions/gradle-4.1-rc-1-all.zip`

I also have another project that builds fine using the older version "milestone-1" `https://services.gradle.org/distributions/gradle-4.1-milestone-1-all.zip`

This is the only difference I can see between the two projects where one fails and one doesnt

**Comment by viktorbenei** [comment]
Could you please copy paste the whole step log here?

**Comment by scruffyfox** [comment]
```
+------------------------------------------------------------------------------+
| (6) gradle-runner@1.7.6                                                      |
+------------------------------------------------------------------------------+
| id: gradle-runner                                                            |
| version: 1.7.6                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2017-08-11T10:47:46Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
[34mINFO[0m[10:47:46] Start installing (golang) with apt-get       
[34mINFO[0m[10:47:46]  * [32;1m[OK][0m Step dependency (go) installed, available. 
[34;1mConfigs:[0m
- GradlewPath: ./gradlew
- GradleFile: build.gradle
- GradleTasks: assembleDebug
- GradleOptions: --stacktrace --no-daemon
- ApkFileIncludeFilter: *.apk
- ApkFileExcludeFilter: *-unaligned.apk
- MappingFileIncludeFilter: */mapping.txt
- MappingFileExcludeFilter: 
- DeployDir: /bitrise/deploy
- CacheLevel: all
[34;1mRunning gradle task...[0m
./gradlew "--build-file" "build.gradle" "assembleDebug" "--stacktrace" "--no-daemon"

Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
[31;1mGradle task failed, error: exit status 1[0m
|                                                                              |
+---+---------------------------------------------------------------+----------+
| [31;1mx[0m | [31;1mgradle-runner@1.7.6 (exit code: 1)[0m                            | 3.86 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-gradle-runner/issues      |
| Source: https://github.com/bitrise-io/steps-gradle-runner                    |
+---+---------------------------------------------------------------+----------+
```

My build workflow (which was copied from the project that builds correctly)

```
---
format_version: '3'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: android
trigger_map:
- push_branch: develop
  workflow: primary
- pull_request_source_branch: "*"
  workflow: primary
workflows:
  primary:
    steps:
    - activate-ssh-key@3.1.1:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@3.5.0: {}
    - cache-pull@1.0.0: {}
    - script@1.1.4:
        title: Do anything with Script step
    - install-missing-android-tools@1.0.3: {}
    - gradle-runner@1.7.6:
        inputs:
        - gradle_file: "$GRADLE_BUILD_FILE_PATH"
        - gradle_task: assembleDebug
        - gradlew_path: "$GRADLEW_PATH"
    - deploy-to-bitrise-io@1.3.6:
        inputs:
        - notify_user_groups: testers
    - cache-push@1.1.3: {}
    - script@1.1.4:
        title: Install AWSCLI
        inputs:
        - content: sudo apt-get install -y awscli
    - amazon-s3-uploader@1.0.1:
        inputs:
        - file_path: "$BITRISE_APK_PATH"
        - aws_access_key: "$AWS_ACCESS_KEY"
        - aws_secret_key: "$AWS_SECRET_KEY"
        - bucket_name: bitrise-builds
        - bucket_region: eu-west-1
        - path_in_bucket: "${BITRISE_BUILD_SLUG}/${BITRISE_BUILD_NUMBER}"
app:
  envs:
  - opts:
      is_expand: false
    GRADLE_BUILD_FILE_PATH: build.gradle
  - opts:
      is_expand: false
    GRADLEW_PATH: "./gradlew"
```

---

Separate issue but also when I set this new project up, the default workflow set the version to '4' but bitrise threw an error 

```
WARN[09:44:06] The bitrise.yml has a higher Format Version (4) than the bitrise CLI model's version (3). 
FATA[09:44:07] Failed to create bitrise config, error: This bitrise.yml was created with and for a newer version of bitrise CLI, please upgrade your bitrise CLI to use this bitrise.
